### PR TITLE
New sponsor logos

### PR DESCRIPTION
**Pull request by redsn0w422**

### CODE REVIEW

**Comment by sskhandek** [comment]
Did you actually check this before you pushed? These don't look very good: 

screen shot 2016-08-15 at 10 18 59 pm
screen shot 2016-08-15 at 10 19 17 pm

**Comment by redsn0w422** [comment]
Yeah I messaged you about how the styling got messed up; I was wondering why the old CSS styles didn't apply to the SVG logos

**Comment by sskhandek** [comment]
I mean that's kinda for you to find out :p I recently added a whole lot of new logos to the site, so I can merge this manually later

**Comment by redsn0w422** [comment]
Haha okay I'll rebase with the new logos and try to fix up the styling

**Comment by akleiner2** [comment]
Can you add screenshots to this? @redsn0w422

**Comment by redsn0w422** [comment]
image

image

image

**Comment by akleiner2** [comment]
Sweet, thanks @redsn0w422. Have you tried this out in different browsers/browser sizes?

**Comment by redsn0w422** [comment]
Not browsers, but I did test mobile.

**Comment by sskhandek** [comment]
@redsn0w422 , I'll merge this into master, but what's with the giant change in the index.html file?

**Comment by redsn0w422** [comment]
I think it might be the rebase? there was a merge conflict and I just deleted the old version

**Comment by sskhandek** [comment]
@redsn0w422 , I doubled checked to make sure everything's okay, but please be careful when doing that. If there merge conflicts, its because its informing you that theres newly inserted code and you have to figure out how to preserve those changes.

**Pull request merged**
