### PR TITLE
simon's text godliness

### PR DESCRIPTION
**Pull request by sskhandek**

### CODE REVIEW

**Comment by bluedrops** [comment]
u flatter me

**Comment by vpahwa** [comment]
Heads up- when you click on the speaker card repeatedly, it just keeps going up and down until meeting all clicks.. Also, we should add Siebel 1404 to the cards as location

**Comment by bluedrops** [comment]
@vpahwa You want 'Siebel 1404' added to every single card? Where specifically on each card?

**Comment by vpahwa** [comment]
Ehh just a thought. We need to put it somewhere (or in multiple places so
people don't miss it). Thoughts?

**Comment by bluedrops** [comment]
hmm, are all speakers guaranteed to be in 1404? We could maybe add a line above or under the speakers section that says "All speakers will be speaking in Siebel 1404; check the schedule for times!" and then also put it somewhere in the FAQ. iunno; it just seems kinda redundant to put the same location on every card haha

**Comment by bluedrops** [comment]
Ooh, alternatively we could put the location AND the time on each speaker card; that way there would be useful information on each one

**Comment by bluedrops** [comment]
what do you think? Just let me know and I'll make it happen :)

**Comment by vpahwa** [comment]
That's what I was thinking! (the latter)

On Sun, Sep 4, 2016 at 11:45 AM, Simon <notifications@github.com> wrote:

> what do you think? Just let me know and I'll make it happen :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_acm-2Duiuc_rp2016_pull_109-23issuecomment-2D244613836&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=q9dhFQaikxAKpExbrpo2iCjb6jjvRL-HIkOpE44UjfE&s=lDBdJe50Dul0TA73T4YzIb3eCRwh3DlGT4rJO0c86Wc&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIZ9WJxeP3eMPDoAdNfFH1R4HSXl0mPIks5qmvWZgaJpZM4JzViU&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=q9dhFQaikxAKpExbrpo2iCjb6jjvRL-HIkOpE44UjfE&s=dhtSZekJoGkkmd4jOmIf-tIZZnDV-1weExDSuYuf4Fs&e=>
> .
>



-- 
Vaibhav Pahwa

*UIUC Computer Science + Statistics 2018*
*Reflections|Projections Co-Chair*
*Freelance Product Manager @ Gigster (YC S15)*

**Pull request merged**
