### PR TITLE
Add locations to the schedule items [#135]

### PR DESCRIPTION
**Pull request by sameetandpotatoes**
locations

@sskhandek Do those locations look right?

https://github.com/acm-uiuc/rp2016/issues/135

### CODE REVIEW

**Comment by sskhandek** [comment]
Looks good! Could you make it "Siebel 1404" and does it look good on other sized screens?

**Comment by sameetandpotatoes** [comment]
Just changed it to "Siebel 1404". Yeah it looked good on a monitor, a laptop, and mobile device. The location always showed up as "subtext" right below the event name. For example:

screen shot 2016-09-10 at 11 55 50 pm

**Comment by sskhandek** [comment]
Okay that looks great. Can you quickly also decrease the font size of the
location?

**Comment by sameetandpotatoes** [comment]
Yep, just reduced it to 12px

**Comment by sskhandek** [comment]
Thanks!

**Pull request merged**
