### PR TITLE
Reduce font size of bios

### PR DESCRIPTION
**Pull request by sameetandpotatoes**
- Just removed the last 2 sentences

### CODE REVIEW

**Comment by vpahwa** [comment]
Umm, is there a way we can just shrink the text a bit instead? I'd rather
not take away from a speaker's bio given that's what they sent us.

On Tue, Sep 27, 2016 at 11:52 AM, Sameet Sapra <notifications@github.com>
wrote:

> Assigned #271
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_acm-2Duiuc_rp2016_pull_271&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=cXomtBf0jW7X1C333EAePLUaCQbOVWHnRflOuuGcOqI&s=FqEPf9U_jk30rJtx8uOsYnlNiOUSgZPEjLUA_rJM8Hk&e=>
> to @vpahwa
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vpahwa&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=cXomtBf0jW7X1C333EAePLUaCQbOVWHnRflOuuGcOqI&s=MIaeLThRPNvDZWbFHxqt_FidL74Hx1q8fpFNODr1l4w&e=>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_acm-2Duiuc_rp2016_pull_271-23event-2D804154758&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=cXomtBf0jW7X1C333EAePLUaCQbOVWHnRflOuuGcOqI&s=OnuYhpQUucYbGdNWrMhNSVQO1RlD-qPp97XgFvQmMrQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIZ9WIyXaenMNJy-2DAiCjdleE-2DjezZ27kks5quUnXgaJpZM4KH50G&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=cXomtBf0jW7X1C333EAePLUaCQbOVWHnRflOuuGcOqI&s=0sYqF_O1SYQ40epS5Kxst7afHuwpE8NBu1EWPCpCdQg&e=>
> .
>



-- 
Vaibhav Pahwa

*UIUC Computer Science + Statistics 2018*
*Reflections|Projections Co-Chair*
*Freelance Product Manager @ Gigster (YC S15)*

**Comment by sameetandpotatoes** [comment]
Oh, wouldn't that be weird since that would be the only bio with a smaller font size?

**Comment by vpahwa** [comment]
Yeah if that was the case, then it would be for all of them. Otherwise, we
can leave it as is but I'd ideally not alter a speaker bio

**Comment by sameetandpotatoes** [comment]
No, that makes sense. I fixed it to just reduce the font size a bit. Looks like this now:

screen shot 2016-09-27 at 1 05 23 pm

**Comment by vpahwa** [comment]
Awesome. Looks much better, thanks!

**Pull request merged**
