### PR TITLE
responsive header stuff

### PR DESCRIPTION
**Pull request by devinho**
Changes: 
- small adjustments to header html
- breakpoints for responsiveness

Notes:
- wasn't too sure about changing input box placeholder. someone who's more familiar with the code might want to take a look

Responsive header: 

responsive-header1

### CODE REVIEW

**Comment by devinho** [comment]
PR for #17

**Comment by sskhandek** [comment]
This looks awesome, but can we adjust the font for the date and the "reflections | projections"? The title should be larger than the dates

**Comment by devinho** [comment]
@sskhandek fixed!

**Comment by sskhandek** [comment]
@devinho beautiful :)

**Pull request merged**
