### PR TITLE
initial responsive nav commit + cleaning up some css

### PR DESCRIPTION
**Pull request by devinho**
Changes:
- Rearranged nav code a bit
- Medium, small size screens get hamburger menu
- Hamburger toggles menu which sticks to top of page (full width)
- Some small CSS code style changes

Notes:
- Code might need some more cleanup
- Small design changes can be made (not sure who has the final say on design), but all functionality should be there

Hamburger-closed:
hamburger

Hamburger-expanded:
hamburger-expanded

### CODE REVIEW

**Comment by devinho** [comment]
For issue #16

**Comment by sskhandek** [comment]
Awesome stuff. I'll merge in a second. Any reason why the background didn't show up for you? @devinho

**Comment by devinho** [comment]
@sskhandek Looks like the path is off. I'll just create a new PR and you can merge that real quick (odd that it doesnt work for just me though)

**Comment by sskhandek** [comment]
@devinho After the user opens the menu, it's a bit hard to see the three lines on the icon since it's black lines on black background. What do you think about inverting the colors on the button it's white lines and a black background?

**Pull request merged**
